<a href="https://colab.research.google.com/github/chetools/CHE4071_Fall2025/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from plotly.subplots import make_subplots

In [6]:
x=np.linspace(0,10,21)
y=2*x + 1
y=y+np.random.normal(loc=0, scale=0.75, size=y.size)

In [14]:
fig=make_subplots()
fig.add_scatter(x=x, y=y, mode='markers')
fig.add_scatter(x=x, y=A @ c, mode='lines')
fig.update_layout(width=600, height=400,template='plotly_dark')

In [9]:
A = np.c_[x, np.ones_like(x)]

In [10]:
A.T @ A

array([[717.5, 105. ],
       [105. ,  21. ]])

In [11]:
A.T @ y

array([1490.33514544,  226.00512813])

In [13]:
c=np.linalg.solve(A.T @ A, A.T @ y)

In [19]:
x=np.linspace(-2, 2, 51)
y = (x+1.7)*(x-0.1)*(x-1.7)
y=y+np.random.normal(loc=0, scale=0.5, size=y.size)

In [25]:
fig=make_subplots()
fig.add_scatter(x=x, y=y, mode='markers')
fig.add_scatter(x=x, y=A @ c, mode='lines')
fig.update_layout(width=600, height=400,template='plotly_dark')

In [22]:
A = np.c_[x**3, x**2, x, np.ones_like(x)]


array([[5.23701492e+02, 6.75015599e-14, 1.76426598e+02, 4.44089210e-15],
       [6.75015599e-14, 1.76426598e+02, 8.88178420e-15, 7.07200000e+01],
       [1.76426598e+02, 8.88178420e-15, 7.07200000e+01, 0.00000000e+00],
       [4.44089210e-15, 7.07200000e+01, 0.00000000e+00, 5.10000000e+01]])

In [24]:
c=np.linalg.solve(A.T @ A, A.T @ y)